### ISSUE TITLE
[1.18.2] Forge 40.0.18 breaks the mod

### ISSUE THREAD

**Issue by Baggytrousers27** [North-West-Wind/MoreBoots#12]
More Boots (moreboots) has failed to load correctly
java.lang.InvocationTargetException: null

Forge 40.0.18
moreboots-3.1.0-1.18.x

[Crashlog](https://pastebin.com/iAkUbjNP)

**Comment by yinzhi24** [comment]
You could update forge to the latest version, just keep in mind that it's unstable!

**Comment by yinzhi24** [comment]
If it works, tell me and I'll close this issue

**Comment by Baggytrousers27** [comment]
Afraid not.
[40.0.19 crashlog](https://pastebin.com/k34UTjnr)

**Comment by yinzhi24** [comment]
Ok, I will tell the developer about the issue. Thanks for reporting it! We will get this fixed as soon as possible!

**Comment by yinzhi24** [comment]
This bug will be fixed in a week or two, in the meantime, please join the Discord on README.md!

**Comment by North-West-Wind** [comment]
Fixed in v3.1.1. Please download the 1.18.x version.
