### ISSUE TITLE
Flower in pot visual glitch

### ISSUE THREAD

**Issue by HeroMeDavid** [North-West-Wind/MoreBoots#2]
**Describe the bug**
For some reason flowers in a flower pots show up as missing texture blocks

**To Reproduce**
Put a flower in a flower pot

**Expected behavior**
the flower pot turns into a missing texture block

**Screenshots**
https://i.imgur.com/Dv6VYbj.png

**Comment by HeroMeDavid** [comment]
to add: I only have this mod instead

**Comment by North-West-Wind** [comment]
I see.
That should be easy to fix, but I'm not sure if I have time for it right now.

Anyway, I will close this now and be sure to look for version 1.3.1 later.
