### ISSUE TITLE
MoreBoots Bug

### ISSUE THREAD

**Issue by FlapJack98to** [North-West-Wind/MoreBoots#3]
Whenever you place a brewing stand down in the world and try to use it, the bottles aren't displaying on it when you exit out the menu and you can't use it at all, it won't start brewing.

Right click a brewing stand to use it but it won't work.

It is supposed to accept the ingredient item and some blaze powder to start brewing a potion.

**Comment by North-West-Wind** [comment]
That should be fixed with v1.4.0
