### ISSUE TITLE
Obsidian Boots issue

### ISSUE THREAD

**Issue by North-West-Wind** [North-West-Wind/MoreBoots#4]
https://www.curseforge.com/minecraft/mc-mods/moreboots#c33

**Comment by AngelVargas11** [comment]
How does it work?

**Comment by North-West-Wind** [comment]
Your items won't lose durability. Instead, the boots lose the durability for the item.

**Comment by North-West-Wind** [comment]
This is so old i dont even know if its relevant anymore. Temporarily closing
