### ISSUE TITLE
Suggestions #2

### ISSUE THREAD

**Issue by yinzhi24** [North-West-Wind/MoreBoots#7]
North-West-Wind, thank you for agreeing to my previous suggestion! (Un)Fortunately, I have more ideas for the mod (I never run out of ideas, gotta use them somewhere), these might be wackier than my previous one, depending on others' opinions.

Number 1: Viscous Boots
This allows you to climb walls (Spider Boots already have that but this one is improved/better), you can't jump while sneaking because you know why. It leaves a trail of stickiness behind. You are also 10% slower for the same reason. If you don't feel like implementing the trail concept, particles also work.

Number 2: Avian Feet
Allows slow-falling, improved speed, and a bit higher jumping. Can be upgraded to Tier 2 described in Number 3.

Number 3: Super Avian Feet (a.k.a. Avian Boots Tier 2)
Same as number 2, but with changes. Not the same as Avian Feet! They can be supercharged to jump WAY higher like Rainbow Socks do, but also has the properties of Viscous Boots, except without debuffs. Instead, the total stats on this bad boi is +25% move speed, +1 block jump height, slow-falling, having a trail, walking on water, and being able to climb walls. This is more expensive to craft though!

Bonus: Tanooki Feet
A reskinned version of Gliders.

Bonus: Turtle Boots
Increases swimming speed and decreases fall damage by a small bit. Crafted with scutes.

Crafting ingredients:
Now, the boots/feet I mentioned above need unique miscellaneous items, are used for crafting them. Here are the ones that are essential for crafting (they have no other use but to craft things):

Golden Feather ![gold feather](https://user-images.githubusercontent.com/69948276/138573977-4b02d627-601d-4cbc-83aa-e92f8e2e3fa9.png): g = gold ingot, f = feather
`ggg`
`gfg`
`ggg`

Viscous Goo (crafts 3) ![goo](https://user-images.githubusercontent.com/69948276/138573981-b3c62ff4-ac25-425e-8a73-9509d409ff77.png): s = slimeball, h = honey block, w = web
`sss`
`whw`
`sss`

Smooth Fabric (crafts 2) ![fabric](https://user-images.githubusercontent.com/69948276/138573983-a5261093-4468-4d38-bc10-28650bb02eb3.png): c = carpet (white), m = magma cream, h = honey block, s = slimeball, b = blue ice
`mmm`
`shs`
`bcb`

Crafting Boots:
Viscous Boots recipe: S = Spider Boots, v = viscous goo (recipe above), s = smooth fabric
`***`
`*S*`
`vsv`

Avian Feet recipe: G = golden feather, i = ice, s = smooth fabric, W = Wind Boots, p = phantom membrane
`pGp`
`GWG`
`sis`

Super Avian Feet recipe: A = Avian Boots, R = Rainbow Socks, p = phantom membrane, v = viscous goo, s = smooth fabric
`RsR`
`vAv`
`sps`

Tanooki Feet recipe: b = brown wool, y = yellow wool, G = Gliders
`b*b`
`bGb`
`byb`

Again, * = left blank

Really appreciate your mod! Take your time!
P.S. I have uploaded the avian boots and super avian feet sprites you can have less work to do, same with the miscellaneous things, and sorry if they are low quality, plus, there will be an "official update name" in my next suggestion which will be coming out in a few days. :)

Files:
Avian Feet item:
![item](https://user-images.githubusercontent.com/69948276/138621956-84a074d5-9d97-4b3c-b1ea-901b75c48627.png)

Avian Feet layout:
![Avian Classic](https://user-images.githubusercontent.com/69948276/138758718-40881c92-17c5-460b-a5ac-911423148e32.png)

Super Avian Feet item:
![item clone](https://user-images.githubusercontent.com/69948276/138621966-47315804-252b-4395-9dde-fa772feabc81.png)

Super Avian Feet layout:
![Magenta Avian](https://user-images.githubusercontent.com/69948276/138758704-75a9b8cc-a478-4742-81c4-ed318bea322f.png)

**Comment by North-West-Wind** [comment]
Done in v3.1.0
